apiVersion: v1
kind: Service
metadata:
  name: jenkins-agent-service
  namespace: jenkins
  labels:
    app: jenkins
spec:
  selector:
    app: jenkins-master
  ports:
    - port: 50000
      targetPort: 50000
      protocol: TCP
      name: agent
  type: ClusterIP
