apiVersion: v1
kind: Service
metadata:
  name: jenkins-ui-service
  namespace: jenkins
  labels:
    app: jenkins
spec:
  selector:
    app: jenkins-master
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  type: LoadBalancer
